title: Foodie Cravings
description: Do you ever have a craving for a certain food while on campus? By using foodie cravings, you will know where
  to get it, if you can get it now, what it looks likes, how much it will cost, and what your fellow students think
  of the food.
theme: jekyll-theme-architect
